"""Render a QueryProfile into the two files a parity case needs.

Split from ``analyse.py`` on purpose. Analysis is where the risk lives -- a
mis-parsed SELECT list makes every output wrong -- so it is separately testable
against a query whose correct answers are already known. This module is
templating, and templating that reads a dataclass is hard to get subtly wrong.

Every generated file carries a header saying it was generated, from what, and
that it is meant to be edited. PRISM is a first draft, not an owner: it cannot
know that a dimension is really a metric in disguise, or that your team spells a
label differently. A generator that pretends otherwise produces files nobody
dares touch.
"""

from __future__ import annotations

import datetime
import os
from typing import Dict, List

from .analyse import QueryProfile

# Where the two files land, relative to whatever root they are written under.
# These mirror the layout the existing case uses; PRISM does not invent a new one.
SQL_DIR = os.path.join("sql", "insight_plus")
CASE_DIR = os.path.join("scripts", "cases_insight_plus")

# PRISM writes into its own folder by default, never into your source tree. You
# generate, read what came out, and copy it into place yourself -- a code
# generator that writes straight into `tests/` on a first run is one you have to
# `git checkout` your way out of.
#
# The output MIRRORS the repo layout rather than being a flat dump, and that is
# forced rather than chosen: the generated YAML carries
# `query_file: ../../sql/insight_plus/<name>.sql`, so the case file has to sit
# two levels under a root that also holds `sql/insight_plus/`. Flatten it and the
# path breaks -- and you could not even run `rowparity list` on the output to
# review it before installing.
OUTPUT_DIR = "output"


def package_dir() -> str:
    return os.path.dirname(os.path.abspath(__file__))


def repo_root() -> str:
    """The rowparity checkout PRISM lives inside."""
    return os.path.dirname(package_dir())


def default_output_root() -> str:
    """``prism/output`` — absolute, so it does not move with the cwd."""
    return os.path.join(package_dir(), OUTPUT_DIR)

# Defaults for the two sides. Overridable, because a second migration will have
# different catalogs -- but defaulted, because for this project they do not.
DEFAULT_EXPECTED_FACTS = "mrm_log_flat.default"
DEFAULT_ACTUAL_FACTS = "etl.public_test1"
DEFAULT_EXPECTED_LABEL = "Hoover"
DEFAULT_ACTUAL_LABEL = "Hoover++"


def _banner(profile: QueryProfile, kind: str) -> str:
    stamp = datetime.date.today().isoformat()
    return (
        f"Generated by PRISM from {profile.sql_path} on {stamp}.\n"
        f"\n"
        f"PRISM derives what the query already states: the keys are its GROUP BY\n"
        f"dimensions, the breakdown column is the one dimension that is a distinct\n"
        f"literal per UNION branch, the unordered arrays are the ones that reach the\n"
        f"output from a source column rather than being constructed inline.\n"
        f"\n"
        f"EDIT THIS FILE. It is a first draft, not a contract. Re-running PRISM\n"
        f"overwrites it, so once you have changed something, stop re-generating and\n"
        f"own it -- or pass --only to regenerate the files you have not touched.\n"
        f"\n"
        f"Source query: {profile.output_columns} output columns "
        f"({len(profile.dimensions)} dimensions + {len(profile.metrics)} metrics), "
        f"{profile.branches} UNION branch(es)."
    )


def _comment(text: str, prefix: str) -> str:
    return "\n".join(f"{prefix} {line}".rstrip() for line in text.splitlines())


# --------------------------------------------------------------------------- #
# 1. the case YAML
# --------------------------------------------------------------------------- #
def render_case_yaml(
    profile: QueryProfile,
    *,
    expected_facts: str = DEFAULT_EXPECTED_FACTS,
    actual_facts: str = DEFAULT_ACTUAL_FACTS,
    expected_label: str = DEFAULT_EXPECTED_LABEL,
    actual_label: str = DEFAULT_ACTUAL_LABEL,
    sampling_filter: str = (
        "bitwise_and(coalesce(request__bit_flags, BIGINT '0'),"
        "bitwise_left_shift(BIGINT '1', 59)) > 0"
    ),
    with_drilldown: bool = True,
) -> str:
    p = profile
    L: List[str] = [_comment(_banner(p, "case"), "#"), ""]
    L += [
        "cases:",
        f"  - name: {p.name}",
        f"    expected_label: {expected_label}",
        f"    actual_label: {actual_label}",
        "    description: >-",
        f"      The {p.name} aggregate must produce identical rows whether built",
        f"      from the {expected_label} layout or the {actual_label} layout. Both",
        "      sides are queries; neither is materialised.",
        "",
    ]

    if "sampling_filter" in p.placeholders:
        L += [
            "    # Shared by BOTH sides, and case-level on purpose: it is the one thing",
            "    # that must never differ. Comparing a sampled side against an unsampled",
            "    # one measures the sampling ratio and nothing else. Defined once and",
            "    # used by both, that bug is not expressible.",
            "    vars:",
            f'      sampling_filter: "{sampling_filter}"',
            "",
        ]

    rel = os.path.relpath(
        os.path.join(SQL_DIR, os.path.basename(p.sql_path)), CASE_DIR
    ).replace(os.sep, "/")
    L += [
        "    # The only difference between the two runs. These outrank --param",
        "    # deliberately: a --param reaching both sides would point them at the",
        "    # same catalog, and a comparison of a table with itself always passes.",
        "    expected:",
        "      type: trino",
        f"      query_file: {rel}",
        "      vars:",
        f"        facts: {expected_facts}",
        "",
        "    actual:",
        "      type: trino",
        f"      query_file: {rel}",
        "      vars:",
        f"        facts: {actual_facts}",
        "",
        "    compare:",
        f"      # The {len(p.dimensions)} GROUP BY dimensions. Not a business key, but unique by",
        "      # construction after the outer aggregation, which is all a key has to be.",
        "      # Keyed, a difference separates into missing/added (a dimension combination",
        "      # is absent) and changed (same dimensions, drifting metrics). Keyless, every",
        "      # difference is missing + added and every column reads as differing.",
        "      keys:",
    ]
    L += [f"        - {d}" for d in p.dimensions]

    if p.unordered_arrays:
        L += [
            "",
            "      # Arrays that reach the output from a source column, whose element",
            "      # order the engine does not guarantee. rowparity treats list as",
            "      # ORDERED by default, so without this a pure ordering difference",
            "      # reads as a data difference.",
        ]
        if p.constructed_arrays:
            L.append(
                "      # Not listed: "
                + ", ".join(p.constructed_arrays)
                + " -- constructed inline, so they cannot vary."
            )
        L.append("      unordered_list_columns:")
        L += [f"        - {c}" for c in p.unordered_arrays]

    L += ["", "      max_examples: 50"]

    if p.breakdown_by:
        L += [
            "",
            "      # Split every difference by which UNION branch produced it. This",
            f"      # column is a hardcoded literal per branch ({', '.join(repr(v) for v in p.breakdown_values)}),",
            "      # so it partitions the output exactly -- and because it is also a key,",
            "      # its value is available for missing, added and changed rows alike.",
            f"      breakdown_by: {p.breakdown_by}",
        ]

    L += [
        "",
        "      # Find the single key column whose drift turned one logical row into a",
        "      # missing + added pair. Costs no warehouse time: it re-pairs key tuples",
        "      # already in memory.",
        "      near_miss: true",
    ]

    if p.row_summary:
        L += [
            "",
            "    # How a differing row is digested in the report, instead of dumping a",
            f"    # {p.output_columns}-column dict truncated after the first four.",
            "    # DERIVED FROM COLUMN NAMES, not from the query -- review these.",
            "    row_summary:",
        ]
        for g in p.row_summary:
            cols = ", ".join(g["columns"])
            L.append(f'      - {{label: "{g["label"]}", columns: [{cols}]}}')

    if with_drilldown and p.batch_param:
        dd = os.path.relpath(
            os.path.join(SQL_DIR, f"{p.name}_drilldown.sql"), CASE_DIR
        ).replace(os.sep, "/")
        L += [
            "",
            "    # Per-row investigation SQL, generated but NOT executed -- running both",
            "    # sides was tried and taken back out: the two scans dominated the parity",
            "    # run they were meant to annotate.",
            "    drilldown:",
            f"      query_file: {dd}",
            "      # An output alias mapped to its SOURCE expression: the alias is not",
            "      # what a predicate against the raw table can filter on. Exactly one",
            "      # column, because the generated predicate is an IN-list over its values.",
            "      bind:",
            "        creative_id: \"if(network_is_ad_owner, coalesce(advertisement__creative_id, -1), -1)\"",
            "      id_column: request__transaction_id",
            "      # Missing rows only: 'this did not arrive, where did its transactions",
            "      # go?' is the question a drill-down is opened to answer.",
            "      kinds: [missing]",
            "      # DERIVED from the run's batch parameter, never typed in. A hardcoded",
            "      # date goes stale the moment you drill a different batch, and nothing",
            "      # in the output says the window was wrong.",
            "      time:",
            f"        param: {p.batch_param}",
            '        format: "%Y%m%d%H%M%S"',
            "        hours_before: 1",
            "        hours_after: 3",
            "      # Deliberately ASYMMETRIC: the migrated side is pinned to the batch",
            "      # hour, the source side searched wider, because 'the event_date",
            "      # shifted' is the hypothesis under test. Pinning both assumes the answer.",
            "      vars:",
            "        expected:",
            "          time_filter: >-",
            "            date_trunc('HOUR', cast(ack__timestamp as timestamp)) >= timestamp '${batch_hour_start}'",
            "            and date_trunc('HOUR', cast(ack__timestamp as timestamp)) < timestamp '${batch_hour_end}'",
            "        actual:",
            "          time_filter: >-",
            "            date_trunc('HOUR', cast(ack__timestamp as timestamp)) = timestamp '${batch_hour}'",
        ]

    L += ["", "    tags: [insight_plus, prism]", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# 2. the drill-down SQL
# --------------------------------------------------------------------------- #
def render_drilldown_sql(profile: QueryProfile) -> str:
    p = profile
    table = p.fact_tables[-1] if p.fact_tables else "ack"
    dims = [d for d in ("network_id", "site_id", "creative_id", "ad_id", "deal_id")
            if d in p.dimensions]
    return f"""-- {_banner(p, "sql").splitlines()[0]}
--
-- Which {'{'}id_column{'}'} sit behind one differing row.
--
-- The parity query is a GROUP BY over {len(p.dimensions)} dimensions, so every per-request
-- identifier is collapsed by the aggregation: one output row summarises many
-- requests and there is no single transaction id to report. This recovers them.
--
-- Three placeholders, filled in by rowparity (written without the dollar-brace
-- because params.py substitutes TEXT, not SQL -- a placeholder spelled out in a
-- comment is a real substitution site):
--
--   facts        the side's catalog+schema, from that side's vars:
--   row_filter   the IN-list over the bound column's differing values
--   time_filter  the side's time/batch window
--
-- The time filter is deliberately ASYMMETRIC. The migrated side is pinned to the
-- hour the parity row claims; the source side is searched over a wider window,
-- because "the event_date shifted between the layouts" is the hypothesis under
-- test. Pinning both sides to the same hour assumes the answer.
--
-- The sampling filter is NOT applied here. This query looks for specific
-- transactions behind one already-identified row; excluding 511/512 of them
-- would usually return nothing and read as "the row does not exist".
--
-- TODO(you): the branch predicates below are the part PRISM cannot derive. Copy
-- them VERBATIM from the WHERE clause of the parity query's relevant branch. If
-- they drift, this looks at a different population than the row it is meant to
-- explain, and nothing in the output says so.

select
    request__transaction_id,
{chr(10).join(f'    {d},' for d in dims)}
    date_trunc('HOUR', cast(ack__timestamp as timestamp)) as event_date,
    process_batch_id,
    count(*) as n
from ${{facts}}.{table}
-- TODO(you): if the parity query unnests an array to reach these dimensions,
-- the same CROSS JOIN UNNEST (...) AS nw (...) block belongs here.
where
    ${{time_filter}}
    -- The differing rows, as one IN-list. Only the bound column is filtered on:
    -- adding more dimensions narrows the result but risks excluding the very
    -- rows whose dimensions drifted, which is what is being looked for.
    and ${{row_filter}}
    -- TODO(you): the branch predicates, copied verbatim from the parity query.
group by {', '.join(str(i) for i in range(1, len(dims) + 4))}
order by 1
"""


# --------------------------------------------------------------------------- #
# Writing them out
# --------------------------------------------------------------------------- #
def planned_outputs(profile: QueryProfile, root: str = ".") -> Dict[str, str]:
    """{kind: path} for everything PRISM would write.

    No "case_test" entry and no "sql_sync_test" entry, on purpose. Both used
    to be a file generated per case, identical in shape to every other
    case's, differing only in constants -- CASE_NAME, EXPECTED_FACTS,
    EXPECTED_FACT_REFS, and so on -- that the Case object and its own SQL
    already carry or that a UNION-branch count already derives.
    tests/test_insight_plus_sql_sync.py is the one file that covers both
    concerns for every case: it discovers every YAML under
    scripts/cases_insight_plus/ and parametrizes over the result, so a new
    case is covered the moment this call finishes -- nothing to generate,
    copy, or keep in sync.
    """
    p = profile
    return {
        "case": os.path.join(root, CASE_DIR, f"{p.name}.yaml"),
        "drilldown": os.path.join(root, SQL_DIR, f"{p.name}_drilldown.sql"),
    }


def render_all(profile: QueryProfile, **kw) -> Dict[str, str]:
    """{kind: file contents}."""
    return {
        "case": render_case_yaml(profile, **kw),
        "drilldown": render_drilldown_sql(profile),
    }
