"""Render a QueryProfile into the four files a parity case needs.

Split from ``analyse.py`` on purpose. Analysis is where the risk lives -- a
mis-parsed SELECT list makes every output wrong -- so it is separately testable
against a query whose correct answers are already known. This module is
templating, and templating that reads a dataclass is hard to get subtly wrong.

Every generated file carries a header saying it was generated, from what, and
that it is meant to be edited. PRISM is a first draft, not an owner: it cannot
know that a dimension is really a metric in disguise, or that your team spells a
label differently. A generator that pretends otherwise produces files nobody
dares touch.
"""

from __future__ import annotations

import datetime
import os
from typing import Dict, List

from .analyse import QueryProfile

# Where the four files land, relative to the repo root. These mirror the layout
# the existing case uses; PRISM does not invent a new one.
SQL_DIR = os.path.join("sql", "insight_plus")
CASE_DIR = os.path.join("scripts", "cases_insight_plus")
TEST_DIR = "tests"

# Defaults for the two sides. Overridable, because a second migration will have
# different catalogs -- but defaulted, because for this project they do not.
DEFAULT_EXPECTED_FACTS = "mrm_log_flat.default"
DEFAULT_ACTUAL_FACTS = "etl.public_test1"
DEFAULT_EXPECTED_LABEL = "Hoover"
DEFAULT_ACTUAL_LABEL = "Hoover++"


def _banner(profile: QueryProfile, kind: str) -> str:
    stamp = datetime.date.today().isoformat()
    return (
        f"Generated by PRISM from {profile.sql_path} on {stamp}.\n"
        f"\n"
        f"PRISM derives what the query already states: the keys are its GROUP BY\n"
        f"dimensions, the breakdown column is the one dimension that is a distinct\n"
        f"literal per UNION branch, the unordered arrays are the ones that reach the\n"
        f"output from a source column rather than being constructed inline.\n"
        f"\n"
        f"EDIT THIS FILE. It is a first draft, not a contract. Re-running PRISM\n"
        f"overwrites it, so once you have changed something, stop re-generating and\n"
        f"own it -- or pass --only to regenerate the files you have not touched.\n"
        f"\n"
        f"Source query: {profile.output_columns} output columns "
        f"({len(profile.dimensions)} dimensions + {len(profile.metrics)} metrics), "
        f"{profile.branches} UNION branch(es)."
    )


def _comment(text: str, prefix: str) -> str:
    return "\n".join(f"{prefix} {line}".rstrip() for line in text.splitlines())


# --------------------------------------------------------------------------- #
# 1. the case YAML
# --------------------------------------------------------------------------- #
def render_case_yaml(
    profile: QueryProfile,
    *,
    expected_facts: str = DEFAULT_EXPECTED_FACTS,
    actual_facts: str = DEFAULT_ACTUAL_FACTS,
    expected_label: str = DEFAULT_EXPECTED_LABEL,
    actual_label: str = DEFAULT_ACTUAL_LABEL,
    sampling_filter: str = (
        "bitwise_and(coalesce(request__bit_flags, BIGINT '0'),"
        "bitwise_left_shift(BIGINT '1', 59)) > 0"
    ),
    with_drilldown: bool = True,
) -> str:
    p = profile
    L: List[str] = [_comment(_banner(p, "case"), "#"), ""]
    L += [
        "cases:",
        f"  - name: {p.name}",
        f"    expected_label: {expected_label}",
        f"    actual_label: {actual_label}",
        "    description: >-",
        f"      The {p.name} aggregate must produce identical rows whether built",
        f"      from the {expected_label} layout or the {actual_label} layout. Both",
        "      sides are queries; neither is materialised.",
        "",
    ]

    if "sampling_filter" in p.placeholders:
        L += [
            "    # Shared by BOTH sides, and case-level on purpose: it is the one thing",
            "    # that must never differ. Comparing a sampled side against an unsampled",
            "    # one measures the sampling ratio and nothing else. Defined once and",
            "    # used by both, that bug is not expressible.",
            "    vars:",
            f'      sampling_filter: "{sampling_filter}"',
            "",
        ]

    rel = os.path.relpath(
        os.path.join(SQL_DIR, os.path.basename(p.sql_path)), CASE_DIR
    ).replace(os.sep, "/")
    L += [
        "    # The only difference between the two runs. These outrank --param",
        "    # deliberately: a --param reaching both sides would point them at the",
        "    # same catalog, and a comparison of a table with itself always passes.",
        "    expected:",
        "      type: trino",
        f"      query_file: {rel}",
        "      vars:",
        f"        facts: {expected_facts}",
        "",
        "    actual:",
        "      type: trino",
        f"      query_file: {rel}",
        "      vars:",
        f"        facts: {actual_facts}",
        "",
        "    compare:",
        f"      # The {len(p.dimensions)} GROUP BY dimensions. Not a business key, but unique by",
        "      # construction after the outer aggregation, which is all a key has to be.",
        "      # Keyed, a difference separates into missing/added (a dimension combination",
        "      # is absent) and changed (same dimensions, drifting metrics). Keyless, every",
        "      # difference is missing + added and every column reads as differing.",
        "      keys:",
    ]
    L += [f"        - {d}" for d in p.dimensions]

    if p.unordered_arrays:
        L += [
            "",
            "      # Arrays that reach the output from a source column, whose element",
            "      # order the engine does not guarantee. rowparity treats list as",
            "      # ORDERED by default, so without this a pure ordering difference",
            "      # reads as a data difference.",
        ]
        if p.constructed_arrays:
            L.append(
                "      # Not listed: "
                + ", ".join(p.constructed_arrays)
                + " -- constructed inline, so they cannot vary."
            )
        L.append("      unordered_list_columns:")
        L += [f"        - {c}" for c in p.unordered_arrays]

    L += ["", "      max_examples: 50"]

    if p.breakdown_by:
        L += [
            "",
            "      # Split every difference by which UNION branch produced it. This",
            f"      # column is a hardcoded literal per branch ({', '.join(repr(v) for v in p.breakdown_values)}),",
            "      # so it partitions the output exactly -- and because it is also a key,",
            "      # its value is available for missing, added and changed rows alike.",
            f"      breakdown_by: {p.breakdown_by}",
        ]

    L += [
        "",
        "      # Find the single key column whose drift turned one logical row into a",
        "      # missing + added pair. Costs no warehouse time: it re-pairs key tuples",
        "      # already in memory.",
        "      near_miss: true",
    ]

    if p.row_summary:
        L += [
            "",
            "    # How a differing row is digested in the report, instead of dumping a",
            f"    # {p.output_columns}-column dict truncated after the first four.",
            "    # DERIVED FROM COLUMN NAMES, not from the query -- review these.",
            "    row_summary:",
        ]
        for g in p.row_summary:
            cols = ", ".join(g["columns"])
            L.append(f'      - {{label: "{g["label"]}", columns: [{cols}]}}')

    if with_drilldown and p.batch_param:
        dd = os.path.relpath(
            os.path.join(SQL_DIR, f"{p.name}_drilldown.sql"), CASE_DIR
        ).replace(os.sep, "/")
        L += [
            "",
            "    # Per-row investigation SQL, generated but NOT executed -- running both",
            "    # sides was tried and taken back out: the two scans dominated the parity",
            "    # run they were meant to annotate.",
            "    drilldown:",
            f"      query_file: {dd}",
            "      # An output alias mapped to its SOURCE expression: the alias is not",
            "      # what a predicate against the raw table can filter on. Exactly one",
            "      # column, because the generated predicate is an IN-list over its values.",
            "      bind:",
            "        creative_id: \"if(network_is_ad_owner, coalesce(advertisement__creative_id, -1), -1)\"",
            "      id_column: request__transaction_id",
            "      # Missing rows only: 'this did not arrive, where did its transactions",
            "      # go?' is the question a drill-down is opened to answer.",
            "      kinds: [missing]",
            "      # DERIVED from the run's batch parameter, never typed in. A hardcoded",
            "      # date goes stale the moment you drill a different batch, and nothing",
            "      # in the output says the window was wrong.",
            "      time:",
            f"        param: {p.batch_param}",
            '        format: "%Y%m%d%H%M%S"',
            "        hours_before: 1",
            "        hours_after: 3",
            "      # Deliberately ASYMMETRIC: the migrated side is pinned to the batch",
            "      # hour, the source side searched wider, because 'the event_date",
            "      # shifted' is the hypothesis under test. Pinning both assumes the answer.",
            "      vars:",
            "        expected:",
            "          time_filter: >-",
            "            date_trunc('HOUR', cast(ack__timestamp as timestamp)) >= timestamp '${batch_hour_start}'",
            "            and date_trunc('HOUR', cast(ack__timestamp as timestamp)) < timestamp '${batch_hour_end}'",
            "        actual:",
            "          time_filter: >-",
            "            date_trunc('HOUR', cast(ack__timestamp as timestamp)) = timestamp '${batch_hour}'",
        ]

    L += ["", "    tags: [insight_plus, prism]", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# 2. the SQL-template test
# --------------------------------------------------------------------------- #
def render_sql_sync_test(profile: QueryProfile, *,
                         expected_facts: str = DEFAULT_EXPECTED_FACTS,
                         actual_facts: str = DEFAULT_ACTUAL_FACTS) -> str:
    p = profile
    body = f'''"""{_banner(p, "test")}

What these guard, and why each is a COUNT rather than a presence check:

* A *set* of placeholder names cannot see a half-converted template. Hardcode
  the catalog or the batch in one of {p.branches} branches and the set is unchanged,
  because the other branches still supply the name. One branch pinned to a stale
  batch reads a different window than the others ON BOTH SIDES, so the totals
  stay plausible, nothing errors, and the drift reads as a migration defect.
* The sampling filter must reach every branch. An unsampled branch contributes
  unsampled rows and skews the aggregate -- and because the other branches are
  still sampled, the total still looks reasonable.
"""
import os
import re

import pytest
import yaml

from rowparity.params import _PLACEHOLDER, substitute

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SQL = os.path.join(ROOT, "sql", "insight_plus", "{p.name}.sql")
CASE = os.path.join(ROOT, "scripts", "cases_insight_plus", "{p.name}.yaml")

EXPECTED_FACTS = "{expected_facts}"
ACTUAL_FACTS = "{actual_facts}"

SAMPLING_MARKER = "--sampling filter"
EXPECTED_SAMPLING_LINES = {p.sampling_markers}   # one per UNION ALL branch
EXPECTED_FACT_REFS = {p.fact_refs}               # {", ".join(p.fact_tables) or "none"}
BATCH_PLACEHOLDER = "${{{p.batch_param}}}"
EXPECTED_BATCH_REFS = {p.batch_refs}             # one predicate per branch
EXPECTED_PLACEHOLDERS = {sorted(p.placeholders)!r}


@pytest.fixture(scope="module")
def sql():
    if not os.path.isfile(SQL):
        pytest.skip(f"{{SQL}} not present")
    with open(SQL, encoding="utf-8") as fh:
        return fh.read()


@pytest.fixture(scope="module")
def case():
    with open(CASE, encoding="utf-8") as fh:
        return yaml.safe_load(fh)["cases"][0]


@pytest.fixture(scope="module")
def variables(case):
    """Exactly what a run resolves, minus the batch id, which has no default."""
    base = dict(case.get("vars") or {{}})
    base["{p.batch_param}"] = "20260812010000"
    return base


def _render(sql_text, variables, facts):
    return substitute(sql_text, {{**variables, "facts": facts}})


class TestTheTemplate:
    def test_it_has_exactly_the_placeholders_we_expect(self, sql):
        # A new placeholder nothing supplies fails at substitution time, which is
        # loud but late -- after credentials are exported and someone is waiting.
        assert sorted(set(_PLACEHOLDER.findall(sql))) == EXPECTED_PLACEHOLDERS

    def test_every_fact_table_goes_through_the_placeholder(self, sql):
        # The highest-value assertion here. One missed reference makes that branch
        # read the same catalog on both sides and silently agree.
        assert sql.count("${{facts}}.") == EXPECTED_FACT_REFS

    def test_every_batch_predicate_goes_through_the_placeholder(self, sql):
        assert sql.count(BATCH_PLACEHOLDER) == EXPECTED_BATCH_REFS

    def test_no_batch_id_is_hardcoded(self, sql):
        literals = re.findall(r"process_batch_id\\s*=\\s*'(\\d{{8,14}})'", sql)
        assert literals == [], f"hardcoded batch id(s): {{literals}}"

    def test_no_catalog_is_hardcoded(self, sql):
        assert EXPECTED_FACTS not in sql
        assert ACTUAL_FACTS not in sql


class TestRenderingBothSides:
    def test_each_side_reads_only_its_own_catalog(self, sql, variables):
        a = _render(sql, variables, EXPECTED_FACTS)
        b = _render(sql, variables, ACTUAL_FACTS)
        assert EXPECTED_FACTS in a and ACTUAL_FACTS not in a
        assert ACTUAL_FACTS in b and EXPECTED_FACTS not in b

    def test_the_two_renders_differ_only_in_the_catalog(self, sql, variables):
        a = _render(sql, variables, EXPECTED_FACTS).replace(EXPECTED_FACTS, "@FACTS@")
        b = _render(sql, variables, ACTUAL_FACTS).replace(ACTUAL_FACTS, "@FACTS@")
        assert a == b

    def test_a_render_leaves_no_placeholder_behind(self, sql, variables):
        assert not _PLACEHOLDER.search(_render(sql, variables, EXPECTED_FACTS))
'''
    if "sampling_filter" in p.placeholders:
        body += '''

class TestBothSidesSampleIdentically:
    """The population guard. A 409x row-count ratio once cost a 77-minute run to
    diagnose: one side sampled, the other not, so every sum was over a different
    number of underlying rows and the run measured the sampling."""

    def test_the_filter_is_case_level_not_per_side(self, case):
        assert "sampling_filter" in (case.get("vars") or {{}})
        for side in ("expected", "actual"):
            assert "sampling_filter" not in (case[side].get("vars") or {{}}), (
                f"{{side}} overrides the sampling filter, so the two sides sample "
                f"differently and the run measures the sampling ratio."
            )

    def test_every_union_branch_is_sampled(self, sql):
        count = sql.count(SAMPLING_MARKER)
        assert count == EXPECTED_SAMPLING_LINES, (
            f"expected {{EXPECTED_SAMPLING_LINES}} sampling filters (one per UNION ALL "
            f"branch), found {{count}}."
        )

    def test_the_filter_reaches_every_branch_when_rendered(self, sql, variables):
        rendered = _render(sql, variables, EXPECTED_FACTS)
        assert rendered.count(variables["sampling_filter"]) == EXPECTED_SAMPLING_LINES
'''
    return body


# --------------------------------------------------------------------------- #
# 3. the wiring test
# --------------------------------------------------------------------------- #
def render_case_test(profile: QueryProfile, *,
                     expected_facts: str = DEFAULT_EXPECTED_FACTS,
                     actual_facts: str = DEFAULT_ACTUAL_FACTS) -> str:
    p = profile
    unordered = repr(p.unordered_arrays)
    return f'''"""{_banner(p, "test")}

Offline only -- no connection is made. These assert the wiring: that the case
loads, that each side resolves to the right query against the right catalog, and
that the batch parameter cannot be skipped.

That last one carries the most weight. An unsubstituted placeholder reaches the
engine inside quotes as a syntactically valid predicate matching no batch. Both
sides return zero rows, the diff finds nothing, and the run reports EQUIVALENT.
A green result proving nothing is the worst outcome available to a verification
tool, so it gets tests.
"""
import os
import re

import pytest
import yaml

from rowparity.cases import Case, discover_cases
from rowparity.params import ParamError, merge_side_vars
from rowparity.sources import resolve_query

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CASES_DIR = os.path.join(REPO, "scripts", "cases_insight_plus")
CASE_FILE = os.path.join(CASES_DIR, "{p.name}.yaml")
SQL_FILE = os.path.join(REPO, "sql", "insight_plus", "{p.name}.sql")

CASE_NAME = "{p.name}"
BATCH = "20260812010000"
BATCH_PARAM = "{p.batch_param}"
PARAMS = {{BATCH_PARAM: BATCH}}

EXPECTED_FACTS = "{expected_facts}"
ACTUAL_FACTS = "{actual_facts}"

EXPECTED_DIMENSIONS = {len(p.dimensions)}
EXPECTED_METRICS = {len(p.metrics)}
EXPECTED_OUTPUT_COLUMNS = {p.output_columns}
UNORDERED_ARRAYS = {unordered}


def _case(params=PARAMS) -> Case:
    for case in discover_cases(CASES_DIR, params):
        if case.name == CASE_NAME:
            return case
    raise AssertionError(f"case {{CASE_NAME!r}} not found in {{CASES_DIR}}")


def _sql(case: Case, side: str) -> str:
    """Render one side exactly as load_source would.

    Both sides read the same file, so the side's own vars: block is what makes
    them different queries. Resolving with case.variables alone would leave
    ${{facts}} unresolved and raise -- which is the point of merging here.
    """
    spec = case.expected if side == "expected" else case.actual
    variables = merge_side_vars(spec.get("vars"), case.variables)
    return resolve_query(spec, os.path.dirname(case.source_file), variables)


@pytest.fixture(scope="module")
def sql_files_present():
    if not os.path.isfile(SQL_FILE):
        pytest.skip(f"{{SQL_FILE}} not present")


class TestWiring:
    def test_case_loads(self, sql_files_present):
        assert _case().name == CASE_NAME

    def test_it_is_a_row_case(self, sql_files_present):
        case = _case()
        assert isinstance(case, Case)
        assert case.expected["type"] == "trino"
        assert case.actual["type"] == "trino"

    def test_default_engine_not_pushdown(self, sql_files_present):
        # breakdown_by and near_miss are computed per row by the default engine;
        # a push-down engine aggregates in-warehouse and never sees one.
        assert _case().engine is None

    def test_the_two_sides_share_one_query_file(self, sql_files_present):
        case = _case()
        assert case.expected["query_file"] == case.actual["query_file"]

    def test_the_sides_differ_only_in_the_fact_catalog(self, sql_files_present):
        case = _case()
        assert case.expected["vars"]["facts"] == EXPECTED_FACTS
        assert case.actual["vars"]["facts"] == ACTUAL_FACTS

    def test_side_vars_carry_no_placeholder(self, sql_files_present):
        # A ${{name}} surviving into a side var could never resolve.
        for side in ("expected", "actual"):
            for value in (getattr(_case(), side).get("vars") or {{}}).values():
                assert "${{" not in str(value)

    def test_listing_works_without_the_batch_parameter(self, sql_files_present):
        # Spec dicts substitute at LOAD time; a run-time value in a load-time
        # slot breaks `rowparity list`.
        assert discover_cases(CASES_DIR, {{}}, resolve_queries=False)

    def test_each_side_reads_its_own_catalog(self, sql_files_present):
        case = _case()
        a, b = _sql(case, "expected"), _sql(case, "actual")
        assert EXPECTED_FACTS in a and ACTUAL_FACTS not in a
        assert ACTUAL_FACTS in b and EXPECTED_FACTS not in b


class TestBatchParameter:
    def test_it_substitutes_on_both_sides(self, sql_files_present):
        case = _case()
        for side in ("expected", "actual"):
            sql = _sql(case, side)
            assert BATCH in sql, side
            assert BATCH_PARAM not in sql, f"{{side}} still carries the placeholder"

    def test_omitting_it_raises_rather_than_running(self, sql_files_present):
        # The false-pass guard. Silence here is what produces a green run over
        # zero rows.
        with pytest.raises(ParamError) as exc:
            _sql(_case(params={{}}), "expected")
        assert BATCH_PARAM in str(exc.value)

    def test_the_yaml_ships_no_default_batch(self, sql_files_present):
        # A literal default names a batch that ages out, and an aged-out batch
        # returns zero rows on both sides -- equivalent, and meaningless.
        with open(CASE_FILE, encoding="utf-8") as fh:
            doc = yaml.safe_load(fh)
        assert BATCH_PARAM not in (doc.get("vars") or {{}})
        for case in doc["cases"]:
            assert BATCH_PARAM not in (case.get("vars") or {{}})


# --------------------------------------------------------------------------- #
# The SELECT-list parser, INLINED on purpose.
#
# PRISM generated this file and then got out of the way. Importing PRISM here
# would make your test suite depend on a code-generation tool at run time, so
# that CI could not run without it and a change to PRISM could turn a test red
# in a repository that never asked for PRISM at all. Thirty lines duplicated is
# the cheaper trade.
# --------------------------------------------------------------------------- #
def _strip_sql_comments(sql):
    # Before splitting, never after: a comment like "-- no use, could be
    # removed" contains a comma, and splitting first tears the SELECT item in
    # half. Commented-out columns would also be read as real ones.
    sql = re.sub(r"/\\*.*?\\*/", "", sql, flags=re.S)
    return "\\n".join(re.sub(r"--.*$", "", line) for line in sql.splitlines())


def _outer_select_items(sql):
    """The outer SELECT list, split on top-level commas only."""
    body = _strip_sql_comments(sql).split("\\nfrom (", 1)[0]
    body = body[body.rfind("\\nselect") + len("\\nselect"):]
    items, depth, current = [], 0, []
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            items.append("".join(current))
            current = []
        else:
            current.append(ch)
    items.append("".join(current))
    return [i.strip() for i in items if i.strip()]


def _output_name(item):
    m = re.search(r"\\bas\\s+([a-z_][a-z0-9_]*)\\s*$", item, re.I | re.S)
    if m:
        return m.group(1)
    m = re.fullmatch(r"(?:[a-z_][a-z0-9_]*\\.)?([a-z_][a-z0-9_]*)", item.strip(), re.I)
    return m.group(1) if m else None


class TestKeysMatchTheQueryDimensions:
    """The keys are the GROUP BY dimensions.

    The risk keys introduce is silent rot: add a column to the SELECT, forget
    this list, and "the same row" quietly means something else.
    """

    @staticmethod
    def _dimensions_and_metrics():
        with open(SQL_FILE, encoding="utf-8") as fh:
            sql = fh.read()
        dims, metrics, unparsed = [], [], []
        for item in _outer_select_items(sql):
            name = _output_name(item)
            if name is None:
                unparsed.append(item.strip()[:80])
                continue
            (metrics if re.search(r"\\bsum\\s*\\(", item, re.I) else dims).append(name)
        return dims, metrics, unparsed

    def test_the_parser_accounts_for_every_output_column(self, sql_files_present):
        # If this fails, every assertion below is measuring the wrong thing.
        dims, metrics, unparsed = self._dimensions_and_metrics()
        assert unparsed == [], f"could not parse: {{unparsed[:3]}}"
        assert len(dims) == EXPECTED_DIMENSIONS
        assert len(metrics) == EXPECTED_METRICS
        assert len(dims) + len(metrics) == EXPECTED_OUTPUT_COLUMNS

    def test_keys_are_exactly_the_dimensions(self, sql_files_present):
        dims, _, _ = self._dimensions_and_metrics()
        assert sorted(_case().config().keys) == sorted(dims)

    def test_no_metric_is_used_as_a_key(self, sql_files_present):
        # Keying on a sum() makes the key change whenever the data does, which
        # pairs nothing and turns every drift into missing + added.
        _, metrics, _ = self._dimensions_and_metrics()
        assert set(_case().config().keys).isdisjoint(metrics)

    def test_keys_are_unique_names(self, sql_files_present):
        keys = _case().config().keys
        assert len(keys) == len(set(keys))

    def test_the_case_is_keyed_not_keyless(self, sql_files_present):
        assert _case().config().keys, "keys were dropped; the report loses attribution"

    @pytest.mark.skipif(not UNORDERED_ARRAYS, reason="no source-order arrays in this query")
    def test_source_ordered_arrays_are_compared_unordered(self, sql_files_present):
        # These are in the key, so their canonical form decides which rows pair.
        # A different element order on the two sides makes one group look like two.
        cfg = _case().config()
        for column in UNORDERED_ARRAYS:
            assert column in cfg.keys
            assert column in set(cfg.unordered_list_columns)
'''


# --------------------------------------------------------------------------- #
# 4. the drill-down SQL
# --------------------------------------------------------------------------- #
def render_drilldown_sql(profile: QueryProfile) -> str:
    p = profile
    table = p.fact_tables[-1] if p.fact_tables else "ack"
    dims = [d for d in ("network_id", "site_id", "creative_id", "ad_id", "deal_id")
            if d in p.dimensions]
    return f"""-- {_banner(p, "sql").splitlines()[0]}
--
-- Which {'{'}id_column{'}'} sit behind one differing row.
--
-- The parity query is a GROUP BY over {len(p.dimensions)} dimensions, so every per-request
-- identifier is collapsed by the aggregation: one output row summarises many
-- requests and there is no single transaction id to report. This recovers them.
--
-- Three placeholders, filled in by rowparity (written without the dollar-brace
-- because params.py substitutes TEXT, not SQL -- a placeholder spelled out in a
-- comment is a real substitution site):
--
--   facts        the side's catalog+schema, from that side's vars:
--   row_filter   the IN-list over the bound column's differing values
--   time_filter  the side's time/batch window
--
-- The time filter is deliberately ASYMMETRIC. The migrated side is pinned to the
-- hour the parity row claims; the source side is searched over a wider window,
-- because "the event_date shifted between the layouts" is the hypothesis under
-- test. Pinning both sides to the same hour assumes the answer.
--
-- The sampling filter is NOT applied here. This query looks for specific
-- transactions behind one already-identified row; excluding 511/512 of them
-- would usually return nothing and read as "the row does not exist".
--
-- TODO(you): the branch predicates below are the part PRISM cannot derive. Copy
-- them VERBATIM from the WHERE clause of the parity query's relevant branch. If
-- they drift, this looks at a different population than the row it is meant to
-- explain, and nothing in the output says so.

select
    request__transaction_id,
{chr(10).join(f'    {d},' for d in dims)}
    date_trunc('HOUR', cast(ack__timestamp as timestamp)) as event_date,
    process_batch_id,
    count(*) as n
from ${{facts}}.{table}
-- TODO(you): if the parity query unnests an array to reach these dimensions,
-- the same CROSS JOIN UNNEST (...) AS nw (...) block belongs here.
where
    ${{time_filter}}
    -- The differing rows, as one IN-list. Only the bound column is filtered on:
    -- adding more dimensions narrows the result but risks excluding the very
    -- rows whose dimensions drifted, which is what is being looked for.
    and ${{row_filter}}
    -- TODO(you): the branch predicates, copied verbatim from the parity query.
group by {', '.join(str(i) for i in range(1, len(dims) + 4))}
order by 1
"""


# --------------------------------------------------------------------------- #
# Writing them out
# --------------------------------------------------------------------------- #
def planned_outputs(profile: QueryProfile, root: str = ".") -> Dict[str, str]:
    """{kind: path} for everything PRISM would write."""
    p = profile
    return {
        "case": os.path.join(root, CASE_DIR, f"{p.name}.yaml"),
        "sql_sync_test": os.path.join(root, TEST_DIR, f"test_{p.name}_sql_sync.py"),
        "case_test": os.path.join(root, TEST_DIR, f"test_{p.name}_case.py"),
        "drilldown": os.path.join(root, SQL_DIR, f"{p.name}_drilldown.sql"),
    }


def render_all(profile: QueryProfile, **kw) -> Dict[str, str]:
    """{kind: file contents}."""
    return {
        "case": render_case_yaml(profile, **kw),
        "sql_sync_test": render_sql_sync_test(profile, **{
            k: v for k, v in kw.items() if k in ("expected_facts", "actual_facts")}),
        "case_test": render_case_test(profile, **{
            k: v for k, v in kw.items() if k in ("expected_facts", "actual_facts")}),
        "drilldown": render_drilldown_sql(profile),
    }
