"""Presto SQL for published results: the shared tables and each test's typed view.

Diffs from every test share one table, so values are stored as strings in maps
(``key_values``, ``expected_values``, ``actual_values``). A per-test view casts
them back to that test's real column names and types, which is what a data
engineer queries::

    SELECT * FROM rowparity_views.clicks_by_device_diffs WHERE run_id = '...'

Schema names are placeholders until the real catalog is chosen; override them
with ROWPARITY_TABLES_SCHEMA and ROWPARITY_VIEWS_SCHEMA.
"""
from __future__ import annotations

import os
import re
from typing import Dict, List, Optional, Sequence

DEFAULT_TABLES_SCHEMA = "hive.rowparity"
DEFAULT_VIEWS_SCHEMA = "hive.rowparity_views"

# Partition columns come from the S3 path, never from the Parquet file.
PARTITIONS = ("case_name", "run_date", "run_id")


def tables_schema() -> str:
    return os.environ.get("ROWPARITY_TABLES_SCHEMA", DEFAULT_TABLES_SCHEMA)


def views_schema() -> str:
    return os.environ.get("ROWPARITY_VIEWS_SCHEMA", DEFAULT_VIEWS_SCHEMA)


def _literal(text: str) -> str:
    return "'" + str(text).replace("'", "''") + "'"


def _ident(name: str) -> str:
    return '"' + str(name).replace('"', '""') + '"'


def view_name(case_name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", case_name.lower()) + "_diffs"


def side_suffix(label: str, fallback: str) -> str:
    """Column suffix for a side label: Hoover -> hoover, Hoover++ -> hooverpp."""
    suffix = re.sub(r"[^a-z0-9]+", "_", label.lower().replace("+", "p")).strip("_")
    return suffix or fallback


def presto_type(arrow_type: str) -> str:
    """Presto type for an Arrow type as ``str(pa.DataType)`` spells it."""
    t = arrow_type.strip()
    simple = {
        "int8": "tinyint", "int16": "smallint", "int32": "integer", "int64": "bigint",
        "uint8": "smallint", "uint16": "integer", "uint32": "bigint", "uint64": "decimal(20,0)",
        "halffloat": "real", "float": "real", "double": "double",
        "bool": "boolean", "string": "varchar", "large_string": "varchar", "date32[day]": "date",
    }
    if t in simple:
        return simple[t]
    if t.startswith("timestamp["):
        return "timestamp with time zone" if "tz=" in t else "timestamp"
    match = re.fullmatch(r"decimal(?:128|256)?\((\d+),\s*(\d+)\)", t)
    if match:
        return f"decimal({match.group(1)},{match.group(2)})"
    match = re.fullmatch(r"(?:large_)?list<[^:]+:\s*(.+)>", t)
    if match:
        inner_arrow = match.group(1).strip()
        inner = presto_type(inner_arrow)
        if inner == "varchar" and inner_arrow not in ("string", "large_string"):
            return "varchar"  # an element type Presto cannot be cast to: keep the JSON text
        return f"array({inner})"
    return "varchar"


def _cast(expr: str, arrow_type: Optional[str]) -> str:
    target = presto_type(arrow_type or "string")
    if target == "varchar":
        return expr
    if target.startswith("array("):
        return f"try_cast(json_parse({expr}) AS {target})"
    return f"try_cast({expr} AS {target})"


def diffs_view_sql(
    case_name: str,
    keys: Optional[Sequence[str]],
    compared_columns: Sequence[str],
    expected_types: Dict[str, str],
    actual_types: Dict[str, str],
    expected_label: str = "expected",
    actual_label: str = "actual",
    tables: Optional[str] = None,
    views: Optional[str] = None,
) -> str:
    tables = tables or tables_schema()
    views = views or views_schema()
    exp_sfx = side_suffix(expected_label, "expected")
    act_sfx = side_suffix(actual_label, "actual")
    if exp_sfx == act_sfx:
        exp_sfx, act_sfx = "expected", "actual"

    lines: List[str] = [
        "run_date", "run_id", "diff_kind", "finding_id", "pair_id", "changed_columns",
    ]
    key_list = list(keys or [])
    for k in key_list:
        lines.append(f"{_cast(f'key_values[{_literal(k)}]', expected_types.get(k))} AS {_ident(k)}")
    for c in compared_columns:
        if c in key_list:
            continue
        lines.append(
            f"{_cast(f'expected_values[{_literal(c)}]', expected_types.get(c))} AS {_ident(f'{c}_{exp_sfx}')}"
        )
        lines.append(
            f"{_cast(f'actual_values[{_literal(c)}]', actual_types.get(c) or expected_types.get(c))}"
            f" AS {_ident(f'{c}_{act_sfx}')}"
        )
        lines.append(f"contains(changed_columns, {_literal(c)}) AS {_ident(f'{c}_differs')}")

    select = ",\n       ".join(lines)
    return (
        f"CREATE OR REPLACE VIEW {views}.{view_name(case_name)} AS\n"
        f"-- Generated by rowparity for test {case_name}. One row per differing row.\n"
        f"SELECT {select}\n"
        f"FROM {tables}.diffs\n"
        f"WHERE case_name = {_literal(case_name)}"
    )


def diffs_query(case_name: str, run_id: str, views: Optional[str] = None) -> str:
    return (
        f"SELECT * FROM {views or views_schema()}.{view_name(case_name)} "
        f"WHERE run_id = {_literal(run_id)}"
    )


def table_ddl(location: str, tables: Optional[str] = None) -> List[str]:
    """CREATE TABLE statements for the two shared tables, run once by an admin."""
    tables = tables or tables_schema()
    base = location.rstrip("/")
    partitioned = ", ".join(_literal(p) for p in PARTITIONS)
    return [
        f"CREATE TABLE IF NOT EXISTS {tables}.diffs (\n"
        "  diff_kind varchar,\n"
        "  finding_id integer,\n"
        "  pair_id bigint,\n"
        "  key_values map(varchar, varchar),\n"
        "  changed_columns array(varchar),\n"
        "  expected_values map(varchar, varchar),\n"
        "  actual_values map(varchar, varchar),\n"
        "  case_name varchar, run_date varchar, run_id varchar\n"
        f") WITH (format = 'PARQUET', external_location = {_literal(base + '/_tables/diffs/')},\n"
        f"        partitioned_by = ARRAY[{partitioned}])",
        f"CREATE TABLE IF NOT EXISTS {tables}.run_summary (\n"
        "  run_ts timestamp,\n"
        "  status varchar,\n"
        "  passed boolean,\n"
        "  expected_rows bigint,\n"
        "  actual_rows bigint,\n"
        "  missing bigint,\n"
        "  added bigint,\n"
        "  changed bigint,\n"
        "  total_differences bigint,\n"
        "  diff_ratio double,\n"
        "  max_diff_ratio double,\n"
        "  keys array(varchar),\n"
        "  keys_inferred boolean,\n"
        "  finding_count integer,\n"
        "  top_finding varchar,\n"
        "  diff_rows_stored bigint,\n"
        "  diff_rows_complete boolean,\n"
        "  expected_sql_sha256 varchar,\n"
        "  actual_sql_sha256 varchar,\n"
        "  error varchar,\n"
        "  result_uri varchar,\n"
        "  diffs_query varchar,\n"
        "  case_name varchar, run_date varchar, run_id varchar\n"
        f") WITH (format = 'PARQUET', external_location = {_literal(base + '/_tables/run_summary/')},\n"
        f"        partitioned_by = ARRAY[{partitioned}])",
    ]
