"""Generated by PRISM from sql/insight_plus/f_demand_mpe_hourly.sql on 2026-09-22.

PRISM derives what the query already states: the keys are its GROUP BY
dimensions, the breakdown column is the one dimension that is a distinct
literal per UNION branch, the unordered arrays are the ones that reach the
output from a source column rather than being constructed inline.

EDIT THIS FILE. It is a first draft, not a contract. Re-running PRISM
overwrites it, so once you have changed something, stop re-generating and
own it -- or pass --only to regenerate the files you have not touched.

Source query: 147 output columns (36 dimensions + 111 metrics), 7 UNION branch(es).

What these guard, and why each is a COUNT rather than a presence check:

* A *set* of placeholder names cannot see a half-converted template. Hardcode
  the catalog or the batch in one of 7 branches and the set is unchanged,
  because the other branches still supply the name. One branch pinned to a stale
  batch reads a different window than the others ON BOTH SIDES, so the totals
  stay plausible, nothing errors, and the drift reads as a migration defect.
* The sampling filter must reach every branch. An unsampled branch contributes
  unsampled rows and skews the aggregate -- and because the other branches are
  still sampled, the total still looks reasonable.
"""
import os
import re

import pytest
import yaml

from rowparity.params import _PLACEHOLDER, substitute

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SQL = os.path.join(ROOT, "sql", "insight_plus", "f_demand_mpe_hourly.sql")
CASE = os.path.join(ROOT, "scripts", "cases_insight_plus", "f_demand_mpe_hourly.yaml")

EXPECTED_FACTS = "mrm_log_flat.default"
ACTUAL_FACTS = "etl.public_test1"

SAMPLING_MARKER = "--sampling filter"
EXPECTED_SAMPLING_LINES = 0   # one per UNION ALL branch
EXPECTED_FACT_REFS = 6               # ack, auction, candidate, slot
BATCH_PLACEHOLDER = "${arena.presto.var.process_batch_id}"
EXPECTED_BATCH_REFS = 7             # one predicate per branch
EXPECTED_PLACEHOLDERS = ['arena.presto.var.process_batch_id', 'facts']


@pytest.fixture(scope="module")
def sql():
    if not os.path.isfile(SQL):
        pytest.skip(f"{SQL} not present")
    with open(SQL, encoding="utf-8") as fh:
        return fh.read()


@pytest.fixture(scope="module")
def case():
    with open(CASE, encoding="utf-8") as fh:
        return yaml.safe_load(fh)["cases"][0]


@pytest.fixture(scope="module")
def variables(case):
    """Exactly what a run resolves, minus the batch id, which has no default."""
    base = dict(case.get("vars") or {})
    base["arena.presto.var.process_batch_id"] = "20260812010000"
    return base


def _render(sql_text, variables, facts):
    return substitute(sql_text, {**variables, "facts": facts})


class TestTheTemplate:
    def test_it_has_exactly_the_placeholders_we_expect(self, sql):
        # A new placeholder nothing supplies fails at substitution time, which is
        # loud but late -- after credentials are exported and someone is waiting.
        assert sorted(set(_PLACEHOLDER.findall(sql))) == EXPECTED_PLACEHOLDERS

    def test_every_fact_table_goes_through_the_placeholder(self, sql):
        # The highest-value assertion here. One missed reference makes that branch
        # read the same catalog on both sides and silently agree.
        assert sql.count("${facts}.") == EXPECTED_FACT_REFS

    def test_every_batch_predicate_goes_through_the_placeholder(self, sql):
        assert sql.count(BATCH_PLACEHOLDER) == EXPECTED_BATCH_REFS

    def test_no_batch_id_is_hardcoded(self, sql):
        literals = re.findall(r"process_batch_id\s*=\s*'(\d{8,14})'", sql)
        assert literals == [], f"hardcoded batch id(s): {literals}"

    def test_no_catalog_is_hardcoded(self, sql):
        assert EXPECTED_FACTS not in sql
        assert ACTUAL_FACTS not in sql


class TestRenderingBothSides:
    def test_each_side_reads_only_its_own_catalog(self, sql, variables):
        a = _render(sql, variables, EXPECTED_FACTS)
        b = _render(sql, variables, ACTUAL_FACTS)
        assert EXPECTED_FACTS in a and ACTUAL_FACTS not in a
        assert ACTUAL_FACTS in b and EXPECTED_FACTS not in b

    def test_the_two_renders_differ_only_in_the_catalog(self, sql, variables):
        a = _render(sql, variables, EXPECTED_FACTS).replace(EXPECTED_FACTS, "@FACTS@")
        b = _render(sql, variables, ACTUAL_FACTS).replace(ACTUAL_FACTS, "@FACTS@")
        assert a == b

    def test_a_render_leaves_no_placeholder_behind(self, sql, variables):
        assert not _PLACEHOLDER.search(_render(sql, variables, EXPECTED_FACTS))
