#!/usr/bin/env python3
"""Generated by scripts/build_hoover_suite.py -- the batch ids for one run.

rowparity.yaml slices every table to one event-hour: the 08:00 batch of the
run date, plus the 2 before it, which between them hold every event
stamped in that hour. This prints those ids as name=value lines.

    $ python batch_params.py 2026-09-18
    batch_id=20260918080000
    batch_id_prev1=...
    batch_id_prev2=...

The scheduler resolves them once per run and pins them on every case with
--param, so one run measures one hour and the cases stay comparable to each
other. Keep this file and rowparity.yaml's slice in step: regenerate both.

A full batch id (YYYYMMDDHHMMSS) works too, and uses that hour rather than
08:00 -- pin one to re-measure an hour that already ran. Pinning batch_id
by hand instead would leave the earlier ids on their defaults, slicing one hour
out of another hour's batches. With no argument it uses today, UTC.
"""

import sys
from datetime import datetime, timedelta, timezone

HOUR = 8
LOOKBACK = 2


def batch_ids(base):
    """The run hour's batch id first, then each earlier batch, newest first."""
    return [(base - timedelta(hours=back)).strftime("%Y%m%d%H%M%S") for back in range(LOOKBACK + 1)]


def base_hour(argument):
    """The hour to measure: a date takes 08:00, a batch id keeps its own."""
    if argument is None:
        today = datetime.now(timezone.utc).date()
        return datetime(today.year, today.month, today.day, HOUR)
    if len(argument) == 14 and argument.isdigit():
        return datetime.strptime(argument, "%Y%m%d%H%M%S")
    day = datetime.strptime(argument, "%Y-%m-%d")
    return datetime(day.year, day.month, day.day, HOUR)


def main(argv):
    if len(argv) > 2:
        print("usage: batch_params.py [YYYY-MM-DD | YYYYMMDDHHMMSS]", file=sys.stderr)
        return 2
    try:
        base = base_hour(argv[1] if len(argv) == 2 else None)
    except ValueError:
        print(f"not a YYYY-MM-DD date or a YYYYMMDDHHMMSS batch id: {argv[1]}", file=sys.stderr)
        return 2
    ids = batch_ids(base)
    print(f"batch_id={ids[0]}")
    for index, value in enumerate(ids[1:], start=1):
        print(f"batch_id_prev{index}={value}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
