name: rowparity_examples
version: "1.0.0"
config-version: 2

profile: rowparity_examples

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
log-path: "logs"
clean-targets: ["target", "dbt_packages"]

models:
  rowparity_examples:
    +materialized: table
