-- Generated by PRISM from sql/insight_plus/f_demand_mpe_hourly.sql on 2026-09-22.
--
-- Which {id_column} sit behind one differing row.
--
-- The parity query is a GROUP BY over 36 dimensions, so every per-request
-- identifier is collapsed by the aggregation: one output row summarises many
-- requests and there is no single transaction id to report. This recovers them.
--
-- Three placeholders, filled in by rowparity (written without the dollar-brace
-- because params.py substitutes TEXT, not SQL -- a placeholder spelled out in a
-- comment is a real substitution site):
--
--   facts        the side's catalog+schema, from that side's vars:
--   row_filter   the IN-list over the bound column's differing values
--   time_filter  the side's time/batch window
--
-- The time filter is deliberately ASYMMETRIC. The migrated side is pinned to the
-- hour the parity row claims; the source side is searched over a wider window,
-- because "the event_date shifted between the layouts" is the hypothesis under
-- test. Pinning both sides to the same hour assumes the answer.
--
-- The sampling filter is NOT applied here. This query looks for specific
-- transactions behind one already-identified row; excluding 511/512 of them
-- would usually return nothing and read as "the row does not exist".
--
-- TODO(you): the branch predicates below are the part PRISM cannot derive. Copy
-- them VERBATIM from the WHERE clause of the parity query's relevant branch. If
-- they drift, this looks at a different population than the row it is meant to
-- explain, and nothing in the output says so.

select
    request__transaction_id,
    network_id,
    date_trunc('HOUR', cast(ack__timestamp as timestamp)) as event_date,
    process_batch_id,
    count(*) as n
from ${facts}.slot
-- TODO(you): if the parity query unnests an array to reach these dimensions,
-- the same CROSS JOIN UNNEST (...) AS nw (...) block belongs here.
where
    ${time_filter}
    -- The differing rows, as one IN-list. Only the bound column is filtered on:
    -- adding more dimensions narrows the result but risks excluding the very
    -- rows whose dimensions drifted, which is what is being looked for.
    and ${row_filter}
    -- TODO(you): the branch predicates, copied verbatim from the parity query.
group by 1, 2, 3, 4
order by 1
